version: '3'

services:
  nginx:
    container_name: rigorTalks-nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
    - "8031:80"
    volumes:
    - .:/app:delegated
    - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - app

  app:
    container_name: rigorTalks-app
    build:
      context: ./etc/infrastructure/app
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
    - ./:/var/www:delegated
    - ./etc/infrastructure/app/custom.ini:/usr/local/etc/php/conf.d/custom.ini:cached
    depends_on:
    - mysql
    - rabbitmq
    env_file:
    - .env

  mysql:
    container_name: rigorTalks-mysql
    image: mariadb:10.4
    restart: unless-stopped
    ports:
    - "3331:3306"
    env_file:
    - .env

  rabbitmq:
    container_name: rigorTalks-rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
    - 5631:5672
    - 15631:15672
    env_file:
    - .env
